

def process(s):
    url_list = filter(lambda d: d.startswith("http"), s.split("\n"))
    return set(url_list)

URLS = {"http://google.com",
        "http://youtube.com",
        "http://facebook.com",
        "http://wikipedia.org",
        "http://yahoo.co.jp",
        "http://amazon.com",
        "http://instagram.com",
        "http://xvideos.com",
        "http://twitter.com",
        "http://pornhub.com",
        "http://yahoo.com",
        "http://yandex.ru",
        "http://xnxx.com",
        "http://reddit.com",
        "http://naver.com",
        "http://live.com",
        "http://vk.com",
        "http://fandom.com",
        "http://whatsapp.com",
        "http://globo.com"
        }

SPECIAL_URLS = process("""
http://www.apple.com/library/test/success.html
http://captive.apple.com/hotspot-detect.html

http://ipv4.download.thinkbroadband.com/5MB.zip
http://ipv4.download.thinkbroadband.com:81/5MB.zip
http://ipv4.download.thinkbroadband.com:8080/5MB.zip

http://www.ovh.net/files/1Mio.dat
http://www.milek.eu.org/
https://linkd.pl/pck2m
https://agiofunds.pl/dokumenty/beta-etf-wig20tr/
https://agiofunds.pl/dokumenty/komentarze/
""")

LIBS_URLS= process("""
https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js
https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js
https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js
https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js
https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js
https://ajax.googleapis.com/ajax/libs/spf/2.4.0/spf.js
https://ajax.googleapis.com/ajax/libs/dojo/1.13.0/dojo/dojo.js
https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.0.js
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.js
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.slim.js
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.slim.min.js
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.slim.min.map
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.js
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.map
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.0.js
https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.js

https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
https://cdn.jsdelivr.net/npm/jquery@3.6.0/AUTHORS.txt
https://cdn.jsdelivr.net/npm/jquery@3.6.0/package.json
https://cdn.jsdelivr.net/npm/jquery@3.2.1/src/core.min.js
https://cdn.jsdelivr.net/npm/jquery@3.2/dist/jquery.min.js
https://cdn.jsdelivr.net/gh/jquery/jquery@3/dist/jquery.min.js
https://cdn.jsdelivr.net/gh/jquery/jquery@3.2/dist/jquery.min.js
https://cdn.jsdelivr.net/wp/plugins/wp-slimstat/tags/4.6.5/wp-slimstat.js

https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.map
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.slim.js

https://code.createjs.com/1.0.0/createjs.min.js
https://code.createjs.com/1.0.0/easeljs.min.js
https://code.createjs.com/1.0.0/tweenjs.min.js
https://code.createjs.com/1.0.0/soundjs.min.js


http://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js
http://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js
http://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js
http://ajax.googleapis.com/ajax/libs/spf/2.4.0/spf.js
http://ajax.googleapis.com/ajax/libs/dojo/1.13.0/dojo/dojo.js
""")



URLS2 = filter(lambda d: d.startswith("http"), """
http://youtube.com
http://amazon.com
http://facebook.com
http://twitter.com
http://fandom.com
http://pinterest.com
http://imdb.com
http://reddit.com
http://yelp.com
http://instagram.com
http://ebay.com
http://walmart.com
http://craigslist.org
http://healthline.com
http://tripadvisor.com
http://linkedin.com
http://webmd.com
http://netflix.com
http://apple.com
http://homedepot.com
http://mail.yahoo.com
http://cnn.com
http://etsy.com
http://google.com
http://yahoo.com
http://indeed.com
http://target.com
http://microsoft.com
http://nytimes.com
http://mayoclinic.org
http://espn.com
http://usps.com
http://quizlet.com
http://gamepedia.com
http://lowes.com
http://irs.gov
http://nih.gov
http://merriam-webster.com
http://steampowered.com
http://mapquest.com
http://foxnews.com
http://allrecipes.com
http://quora.com
http://aol.com
http://britannica.com
http://live.com
http://bestbuy.com
http://rottentomatoes.com
http://ca.gov
http://play.google.com
http://cnet.com
http://roblox.com
http://zillow.com
http://businessinsider.com
http://bulbagarden.net
http://paypal.com
http://finance.yahoo.com
http://genius.com
http://usatoday.com
http://realtor.com
http://medicalnewstoday.com
http://fedex.com
http://bankofamerica.com
http://washingtonpost.com
http://investopedia.com
http://speedtest.net
http://spotify.com
http://cdc.gov
http://chase.com
http://hulu.com
#http://xfinity.com
http://msn.com
http://dictionary.com
http://weather.com
http://ups.com
http://verizon.com
http://forbes.com
http://wowhead.com
http://expedia.com
http://urbandictionary.com
http://foodnetwork.com
http://nbcnews.com
http://macys.com
#http://apartments.com
http://ign.com
http://capitalone.com
http://costco.com
http://theguardian.com
http://cnbc.com
http://glassdoor.com
#http://yellowpages.com
http://att.com
http://bbc.com
http://khanacademy.org
#http://ny.gov
http://twitch.tv
http://adobe.com
http://cbssports.com
""".split("\n"))

URL_TOP100_HTTPS=process("""
https://www.google.com
https://www.youtube.com
https://mail.google.com
https://www.facebook.com
https://twitter.com
https://docs.google.com
https://duckduckgo.com
https://accounts.google.com
https://www.linkedin.com
https://outlook.office.com
https://www.instagram.com
https://drive.google.com
https://web.whatsapp.com
https://github.com
https://www.reddit.com
https://login.microsoftonline.com
https://outlook.live.com
https://www.netflix.com
https://mail.yahoo.com
https://translate.google.com
https://l.facebook.com
https://www.amazon.com
https://en.wikipedia.org
https://www.twitch.tv
https://www.bing.com
https://calendar.google.com
https://stackoverflow.com
https://www.binance.com
https://discord.com
https://coinmarketcap.com
https://www.baidu.com
https://my308053-sso.crm.ondemand.com
https://meet.google.com
https://t.co
https://login.live.com
https://mail-redir.mention.com
https://teams.microsoft.com
https://www.msn.com
https://yandex.ru
https://www.google.fr
https://docs.microsoft.com
https://vk.com
https://www.coingecko.com
https://www.messenger.com
https://www.udemy.com
https://www.google.de
https://www.google.co.uk
https://classroom.google.com
https://www.tradingview.com
https://news.google.com
#https://erp.fxpro.com
https://www.startpage.com
https://app.slack.com
https://www.bbc.co.uk
https://outlook.office365.com
https://www.ebay.com
https://www.yahoo.com
https://crm.ironfx.com
https://www.google.it
https://marketplace.axieinfinity.com
https://www.amazon.de
https://www.xvideos.com
https://www.microsoft.com
https://www.office.com
https://support.google.com
https://www.amazon.co.uk
https://support.microsoft.com
https://www.paypal.com
https://web.telegram.org
https://mail.protonmail.com
https://www.amazon.fr
https://www.imdb.com
https://medium.com
https://www.deepl.com
https://business.facebook.com
https://myaccount.google.com
https://chrome.google.com
https://www.google.es
https://music.youtube.com
https://e.mail.ru
https://us02web.zoom.us
https://accounts.binance.com
https://www.qwant.com
https://blog.csdn.net
https://zoom.us
https://www.quora.com
https://studio.youtube.com
https://atnahs.sharepoint.com
https://www.tiktok.com
https://trello.com
https://www.bilibili.com
https://www.amazon.in
https://www.canva.com
https://www.google.ca
https://www.bbc.com
https://freshdesk.fxpro.com
https://www.cnn.com
https://www.roblox.com
https://store.steampowered.com
https://www.virustotal.com
""")

TOP_100_PL = process("""
http://google.com
http://facebook.com
http://youtube.com
http://wp.pl
http://google.pl
http://onet.pl
http://allegro.pl
http://interia.pl
http://wikipedia.org
http://olx.pl
http://gazeta.pl
http://o2.pl
http://instagram.com
http://pornhub.com
http://ceneo.pl
http://tvn24.pl
http://pudelek.pl
http://cda.pl
http://netflix.com
http://librus.pl
http://wyborcza.pl
http://money.pl
http://otomoto.pl
http://twitter.com
http://filmweb.pl
http://wykop.pl
http://fakt.pl
http://sport.onet.pl
http://businessinsider.com.pl
http://sport.pl
http://ipko.pl
http://medonet.pl
http://xvideos.com
http://se.pl
http://vulcan.net.pl
http://xnxx.com
http://radiozet.pl
http://naszemiasto.pl
http://google.com.br
http://xhamster.com
http://jbzd.com.pl
http://plotek.pl
http://tvp.pl
http://pomponik.pl
http://mbank.pl
http://abczdrowie.pl
http://plejada.pl
http://flashscore.pl
http://sport.interia.pl
http://aliexpress.com
http://demotywatory.pl
http://onnetwork.tv
#http://pikio.pl
http://ingbank.pl
http://mediaexpert.pl
http://joemonster.org
http://poradnikzdrowie.pl
http://otodom.pl
http://messenger.com
http://play.pl
http://lotto.pl
http://gemius.pl
http://linkedin.com
http://pepper.pl
http://ing.pl
http://booking.com
http://centrum24.pl
http://mp.pl
http://dobreprogramy.pl
http://pracuj.pl
http://bankier.pl
http://euro.com.pl
http://pinterest.com
http://twitch.tv
http://redtube.com
http://meczyki.pl
http://zalando.pl
http://plus.pl
http://wprost.pl
http://datezone.com
http://poczta-polska.pl
http://komputerswiat.pl
http://finanse.wp.pl
http://roksa.pl
http://vod.pl
http://telemagazyn.pl
http://sprzedajemy.pl
http://pekao24.pl
http://t-mobile.pl
http://gemius.com
http://bongacams.com
http://kwejk.pl
http://yahoo.com
#http://elektroda.pl
http://brainly.pl
#http://zalukaj.com
http://orange.pl
http://auto-swiat.pl
http://meteo.pl
http://doz.pl
""")

ALL_URLS=set.union(URL_TOP100_HTTPS, URLS2, SPECIAL_URLS, LIBS_URLS, TOP_100_PL)

# URLs known to fail in browsers for browser-specific reasons (Enhanced
# Tracking Protection, strict CSP, opaque-response blocking, etc.) rather
# than actual connectivity problems. The CLI still tests them; the web
# frontend lets users skip them via a checkbox. Extend this list when
# you observe a site consistently failing in Firefox/Chrome despite
# being reachable from curl or the Python CLI.
BROWSER_EXCLUDED = process("""
# Blocked by Firefox Enhanced Tracking Protection (Meta/Yahoo/Yandex/etc.)
https://www.facebook.com
https://l.facebook.com
https://business.facebook.com
https://www.yahoo.com
https://mail.yahoo.com
https://yandex.ru
https://www.tiktok.com
https://www.reddit.com

# Strict CSP / opaque-response blocking observed in Firefox
https://www.bing.com
https://www.quora.com
https://www.qwant.com
https://trello.com
https://music.youtube.com
https://marketplace.axieinfinity.com
https://freshdesk.fxpro.com
""")
