#!/usr/bin/env python3
"""Regenerates web/database.js from database.py.

database.py is the single source of truth for URL corpora. Run this after
editing it, or let CI run it before deploying the web frontend.

Note: database.URLS2 is a filter iterator that database.py consumes while
building ALL_URLS, so it is not exported separately here — the URLs it
contains are reachable via ALL_URLS.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import database  # noqa: E402

OUTPUT = ROOT / "web" / "database.js"

EXPORTED = [
    "URLS",
    "SPECIAL_URLS",
    "LIBS_URLS",
    "URL_TOP100_HTTPS",
    "TOP_100_PL",
]


def dump(name, urls):
    payload = json.dumps(sorted(urls), indent=2)
    return f"export const {name} = {payload};\n"


def main():
    parts = [
        "// Auto-generated by scripts/generate_database_js.py.\n",
        "// Source of truth: database.py. Do not edit this file by hand —\n",
        "// re-run the generator after changing the Python corpus.\n",
        "\n",
    ]
    for name in EXPORTED:
        parts.append(dump(name, getattr(database, name)))
        parts.append("\n")
    parts.append(dump("ALL_URLS", database.ALL_URLS))

    OUTPUT.write_text("".join(parts))
    print(f"Wrote {OUTPUT} ({len(database.ALL_URLS)} URLs in ALL_URLS)")


if __name__ == "__main__":
    main()
